### ISSUE TITLE
Misleading "please retry" message when checks are pending

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nixpkgs-merge-bot#127]
When a check is still pending, the bot will tell you to try again later:

https://github.com/NixOS/nixpkgs-merge-bot/blob/c0cdb5179162ad5637e6a0ae9e5f4864cb341e9b/nixpkgs_merge_bot/commands/merge.py#L141

but it's stated in the nixpkgs README (see https://github.com/NixOS/nixpkgs/pull/305553) that the bot "patiently waits for ofBorg to finish before attempting the merge again".

If the bot will in fact automatically retry the merge once checks are done, the message should probably say something closer to:

> One or more checks are still pending, will automatically retry after they are done (darwin checks are ignored).

**Comment by Mic92** [comment]
At least in theory. I heard in some cases that retry doesn't work.
