### ISSUE TITLE
Unclear checking semantics

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixpkgs-merge-bot#3]
The code in https://github.com/NixOS/nixpkgs-merge-bot/blob/4f5ed7d1dcc0d7424fc0886da294ee9731eb7096/nixpkgs_merge_bot/nix.py doesn't seem right:

- For each file that the PR updates, it takes the _third_ file path component as the attribute. Now that the filter for `pkgs/by-name` files is turned off, this is not sensible anymore.

- It sets the `permitted` multiple times, but only the last result is used. It should use all the results in some way. What happens if the user is a maintainer of only the last file changed in the PR? Seems like the code would allow the merge to proceed.

Some test cases to make sure we understand the semantics better should be there.

**Comment by Lassulus** [comment]
the permitted is always set to false in a branch, so that should be straight forward.
maybe we can change the logic around to be more clear (like start with default false and set it to true if a condition does match)

but decline_reasons doesn't actually merge over multiple branches, so showing all the reasons why a PR was declined would be more sensible

**Comment by infinisil** [comment]
Ah you're right about `permitted`, never mind, that looks fine.

**Comment by Mic92** [comment]
Rely on pkgs/by-name again: https://github.com/NixOS/nixpkgs-merge-bot/pull/4/files

**Comment by Mic92** [comment]
How can we check what attributes have been changed reliable without this check?

**Comment by infinisil** [comment]
r-ryantm should have the information on exactly which attribute was attempted to update, maybe look at what exactly it does and if it exports it somewhere where it's easy to ingest it. It does add the attribute to the PR title, but that sounds very brittle.

**Comment by Lassulus** [comment]
for future compatibility we shouldn't rely on any r-ryantm specific features and should better re-implement the logic

**Comment by infinisil** [comment]
It doesn't make sense to re-implement the logic. r-ryantm takes an attribute name and generates a PR for that. You'd have to go the opposite direction: Take the PR and figure out which attribute name it updates. And this can't be reliably done without something like `pkgs/by-name`.

**Comment by Mic92** [comment]
Ok. So we have just have to wait for this principle to become more widely available?

**Comment by infinisil** [comment]
That would be an option yeah, I'm working on it

**Comment by Lassulus** [comment]
with https://github.com/NixOS/nixpkgs-merge-bot/pull/38 the checking logic should be even more clearer. Is that enough to close this issue?
