### ISSUE TITLE
Require no failing CI check

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixpkgs-merge-bot#35]
The bot should not be able to merge PRs if any CI check is failing.

**Comment by Lassulus** [comment]
I think this is generally a good idea. But I see darwin builds timing out very often. So I would enable this and see if people are frustrated with it and then maybe filter out darwin related issues?

**Comment by mweinelt** [comment]
I think this requires changes to the results ofBorg reports. Timeouts are common, especially so on staging, and shouldn't block a merge. As such they need to be neutral, and ofBorg needs to go to red with actual build failures or something similar.

**Comment by infinisil** [comment]
I intentionally worded this as "No failing check" and not "all checks pass", because ofborg doesn't actually fail checks for timeouts (or any package build failures), it only reports them as neutral: https://github.com/NixOS/nixpkgs/runs/21429060308

So this doesn't mean all checks need to be green, but rather no check has to be red.

**Comment by Lassulus** [comment]
With https://github.com/NixOS/nixpkgs-merge-bot/pull/57 merged I think this issue is now solved in sufficient way and we can close this?

**Comment by infinisil** [comment]
Nice :)
