### ISSUE TITLE
Add a merge timeout feature

### ISSUE THREAD

**Issue by Janik-Haag** [NixOS/nixpkgs-merge-bot#67]
This is probably more a nice to have, a sane default could be something between 5-10mins.

**Comment by Mic92** [comment]
When does the merge timeout starts to count? ofborg can certainly queue evaluation for longer than that.

**Comment by Janik-Haag** [comment]
I would say after the at NixOS/nixpkgs-merge-bot merge oomment,

**Comment by Scriptkiddi** [comment]
What problem are you trying to solve with that feature? That people push commits on a branch while the bot is still waiting for ofborg?

**Comment by Scriptkiddi** [comment]
@Janik-Haag any update other wise I would closely this issue.
