### ISSUE TITLE
Allow commands anywhere in comment

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nixpkgs-merge-bot#76]
unless I'm misunderstanding, it seems like the merge command will only work if it's right at the start of the comment:

https://github.com/NixOS/nixpkgs-merge-bot/blob/f381d8d8c20ae4c70b9be57ac3a426d10cc47ca2/nixpkgs_merge_bot/webhook/issue_comment.py#L30-L32

prior art like @bors is, as far as I know, happy for its commands to be anywhere in the comment, as long as they're in a paragraph of their own

could nixpkgs-merge-bot do the same?

**Comment by Mic92** [comment]
How does one detect paragraphs in text?

**Comment by sersorrel** [comment]
one approach could be to do something like this, for example:

```python
re.search(rf"^@{bot_name}\s+merge$", stripped, re.MULTILINE)
```

which is not quite "paragraphs", but might be close enough

**Comment by sersorrel** [comment]
it seems like @ofborg does much the same thing, allowing commands to appear anywhere as long as they're on a separate line: https://github.com/NixOS/ofborg/blob/eb120ff74c155c990b4f0987649cf4b541d7a17b/ofborg/src/commentparser.rs#L5-L7
