### ISSUE TITLE
broken formatting

### ISSUE THREAD

**Issue by pbsds** [NixOS/nixpkgs-merge-bot#92]
https://github.com/NixOS/nixpkgs/pull/308251#issuecomment-2112992744

**Comment by Mic92** [comment]
Interesting. I don't see this anywhere else.

**Comment by pbsds** [comment]
https://github.com/NixOS/nixpkgs/pull/294036#issuecomment-2028783805

**Comment by pbsds** [comment]
Just floating some ideas:

* `"\n".join("some string that should have been a list of paragraphs")`?
* utf16?
* a 8bit and 16bit `char` x64_64 and aarch64 mismatch?

**Comment by Scriptkiddi** [comment]
I have some free time tomorrow and will fix this

**Comment by Scriptkiddi** [comment]
it took a little bit longer as the I was busy but this fixes the formatting
